"""empty message

Revision ID: 03b384b82d9f
Revises: fc9c1d2d2bc2
Create Date: 2016-12-09 13:28:39.022203

"""

# revision identifiers, used by Alembic.
revision = '03b384b82d9f'
down_revision = 'fc9c1d2d2bc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_analysis_parameters', 'value')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_analysis_parameters', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    ### end Alembic commands ###
