"""empty message

Revision ID: 0879aa2fbba4
Revises: 6f3a152e0d45
Create Date: 2016-12-16 16:11:38.815275

"""

# revision identifiers, used by Alembic.
revision = '0879aa2fbba4'
down_revision = '6f3a152e0d45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_analyses_outputFiles')
    op.add_column('association_analyses_inputFiles', sa.Column('label', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association_analyses_inputFiles', 'label')
    op.create_table('association_analyses_outputFiles',
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], [u'analyses.id'], name=u'association_analyses_outputFiles_analysis_id_fkey'),
    sa.ForeignKeyConstraint(['file_id'], [u'files.id'], name=u'association_analyses_outputFiles_file_id_fkey'),
    sa.PrimaryKeyConstraint('analysis_id', 'file_id', name=u'association_analyses_outputFiles_pkey')
    )
    ### end Alembic commands ###
