"""empty message

Revision ID: 0fb14b9e8f5c
Revises: 50432f7bb214
Create Date: 2016-04-28 16:03:19.451201

"""

# revision identifiers, used by Alembic.
revision = '0fb14b9e8f5c'
down_revision = '50432f7bb214'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('file_description', sa.String(length=255), nullable=True))
    op.add_column('experiment_files', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('experiment_files', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.drop_column('experiment_files', 'filePath')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('filePath', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('experiment_files', 'file_path')
    op.drop_column('experiment_files', 'file_name')
    op.drop_column('experiment_files', 'file_description')
    ### end Alembic commands ###
