"""empty message

Revision ID: 1428cf360aad
Revises: 03b384b82d9f
Create Date: 2016-12-09 13:29:02.533308

"""

# revision identifiers, used by Alembic.
revision = '1428cf360aad'
down_revision = '03b384b82d9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_analysis_parameters', sa.Column('value', sa.Text(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_analysis_parameters', 'value')
    ### end Alembic commands ###
