"""empty message

Revision ID: 14cb7ff04dc5
Revises: 2467192b6882
Create Date: 2017-04-10 13:43:17.900276

"""

# revision identifiers, used by Alembic.
revision = '14cb7ff04dc5'
down_revision = '2467192b6882'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid', sa.String(length=40), nullable=True),
    sa.Column('filename', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('executor', sa.String(length=35), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('output_file_name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plot_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('help', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('format', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plot_inputs')
    op.drop_table('plots')
    ### end Alembic commands ###
