"""empty message

Revision ID: 1cb76cff9beb
Revises: 2b1882924cc2
Create Date: 2017-06-11 13:43:40.655028

"""

# revision identifiers, used by Alembic.
revision = '1cb76cff9beb'
down_revision = '2b1882924cc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_inputs', 'name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('pipeline_outputs', 'name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('pipelines', 'filename',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('pipelines', 'name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('pipelines', 'uid',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipelines', 'uid',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('pipelines', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('pipelines', 'filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('pipeline_outputs', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('pipeline_inputs', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    ### end Alembic commands ###
