"""empty message

Revision ID: 24464b45de58
Revises: 1cb76cff9beb
Create Date: 2017-06-11 17:04:07.209158

"""

# revision identifiers, used by Alembic.
revision = '24464b45de58'
down_revision = '1cb76cff9beb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('display_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'display_name')
    ### end Alembic commands ###
