"""empty message

Revision ID: 2467192b6882
Revises: a4b9b2d59b2e
Create Date: 2017-04-04 10:23:25.324042

"""

# revision identifiers, used by Alembic.
revision = '2467192b6882'
down_revision = 'a4b9b2d59b2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualizations', sa.Column('plot_uid', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visualizations', 'plot_uid')
    ### end Alembic commands ###
