"""empty message

Revision ID: 2b1882924cc2
Revises: fe1945351dd6
Create Date: 2017-06-10 17:04:25.162152

"""

# revision identifiers, used by Alembic.
revision = '2b1882924cc2'
down_revision = 'fe1945351dd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_inputs', 'format',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('pipeline_outputs', 'format',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=255),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_outputs', 'format',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
    op.alter_column('pipeline_inputs', 'format',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
    ### end Alembic commands ###
