"""empty message

Revision ID: 3876cada1598
Revises: a0cfeaf60ee5
Create Date: 2016-04-27 11:12:25.720262

"""

# revision identifiers, used by Alembic.
revision = '3876cada1598'
down_revision = 'a0cfeaf60ee5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'experiment_files', 'experiments', ['experiment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment_files', type_='foreignkey')
    ### end Alembic commands ###
