"""empty message

Revision ID: 38d73f2be28a
Revises: 95132a821866
Create Date: 2016-09-16 14:04:24.354989

"""

# revision identifiers, used by Alembic.
revision = '38d73f2be28a'
down_revision = '95132a821866'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('script', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'experiment_files', sa.Column('mime_type', sa.String(length=255), nullable=True))
    op.drop_column(u'experiment_files', 'mimetype')
    op.drop_column(u'experiment_files', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'experiment_files', sa.Column('type', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column(u'experiment_files', sa.Column('mimetype', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column(u'experiment_files', 'mime_type')
    op.drop_table('pipelines')
    ### end Alembic commands ###
