"""empty message

Revision ID: 41bdbc4d5c01
Revises: c1a82e54f975
Create Date: 2016-08-15 11:24:18.809756

"""

# revision identifiers, used by Alembic.
revision = '41bdbc4d5c01'
down_revision = 'c1a82e54f975'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('file_mimetype', sa.String(length=255), nullable=True))
    op.drop_column('experiment_files', 'file_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('file_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('experiment_files', 'file_mimetype')
    ### end Alembic commands ###
