"""empty message

Revision ID: 46874f0ff69f
Revises: 38d73f2be28a
Create Date: 2016-09-16 17:38:30.641925

"""

# revision identifiers, used by Alembic.
revision = '46874f0ff69f'
down_revision = '38d73f2be28a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_analyses', sa.Column('input_parameters', sa.String(length=255), nullable=False))
    op.add_column('experiment_analyses', sa.Column('output_parameters', sa.String(length=255), nullable=False))
    op.add_column('experiment_analyses', sa.Column('pipeline_id', sa.String(length=255), nullable=False))
    op.drop_constraint(u'experiment_analyses_data_input_fkey', 'experiment_analyses', type_='foreignkey')
    op.drop_column('experiment_analyses', 'data_ouput')
    op.drop_column('experiment_analyses', 'data_input')
    op.drop_column('experiment_analyses', 'command')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_analyses', sa.Column('command', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('experiment_analyses', sa.Column('data_input', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiment_analyses', sa.Column('data_ouput', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key(u'experiment_analyses_data_input_fkey', 'experiment_analyses', 'experiment_files', ['data_input'], ['id'], ondelete=u'CASCADE')
    op.drop_column('experiment_analyses', 'pipeline_id')
    op.drop_column('experiment_analyses', 'output_parameters')
    op.drop_column('experiment_analyses', 'input_parameters')
    ### end Alembic commands ###
