"""empty message

Revision ID: 47879a03e0b7
Revises: 63c358928ccd
Create Date: 2016-09-14 14:25:59.738949

"""

# revision identifiers, used by Alembic.
revision = '47879a03e0b7'
down_revision = '63c358928ccd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('data_input', sa.Integer(), nullable=True),
    sa.Column('data_ouput', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['data_input'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_analyses')
    ### end Alembic commands ###
