"""empty message

Revision ID: 4d827143949e
Revises: 99f907d0363e
Create Date: 2016-08-10 17:59:07.355714

"""

# revision identifiers, used by Alembic.
revision = '4d827143949e'
down_revision = '99f907d0363e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('information', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'information')
    ### end Alembic commands ###
