"""empty message

Revision ID: 50432f7bb214
Revises: 3876cada1598
Create Date: 2016-04-27 11:29:58.989863

"""

# revision identifiers, used by Alembic.
revision = '50432f7bb214'
down_revision = '3876cada1598'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'experiment_files_experiment_id_fkey', 'experiment_files', type_='foreignkey')
    op.create_foreign_key(None, 'experiment_files', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment_files', type_='foreignkey')
    op.create_foreign_key(u'experiment_files_experiment_id_fkey', 'experiment_files', 'experiments', ['experiment_id'], ['id'])
    ### end Alembic commands ###
