"""empty message

Revision ID: 527fafe1239a
Revises: b293dbf40506
Create Date: 2017-05-04 14:52:15.248139

"""

# revision identifiers, used by Alembic.
revision = '527fafe1239a'
down_revision = 'b293dbf40506'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_groups', 'group_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.create_index(op.f('ix_user_groups_group_id'), 'user_groups', ['group_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_groups_group_id'), table_name='user_groups')
    op.alter_column('user_groups', 'group_id',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    ### end Alembic commands ###
