"""empty message

Revision ID: 5c99c39f9ef7
Revises: None
Create Date: 2016-03-31 11:22:47.518639

"""

# revision identifiers, used by Alembic.
revision = '5c99c39f9ef7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('experimenter', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiments')
    ### end Alembic commands ###
