"""empty message

Revision ID: 5da2232ea1fe
Revises: d90179bfb109
Create Date: 2017-09-08 16:08:14.996055

"""

# revision identifiers, used by Alembic.
revision = '5da2232ea1fe'
down_revision = 'd90179bfb109'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'sha')
    op.drop_column('files', 'folder')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('folder', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('sha', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    ### end Alembic commands ###
