"""empty message

Revision ID: 5dfb178a3ad2
Revises: c9be239778ce
Create Date: 2017-04-25 12:01:27.126784

"""

# revision identifiers, used by Alembic.
revision = '5dfb178a3ad2'
down_revision = 'c9be239778ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot_inputs', sa.Column('required', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot_inputs', 'required')
    ### end Alembic commands ###
