"""empty message

Revision ID: 63c358928ccd
Revises: 41bdbc4d5c01
Create Date: 2016-08-15 15:33:06.477025

"""

# revision identifiers, used by Alembic.
revision = '63c358928ccd'
down_revision = '41bdbc4d5c01'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('sha', sa.String(length=40), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('experiment_files')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_group', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('file_mimetype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], [u'experiments.id'], name=u'experiment_files_experiment_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'experiment_files_pkey')
    )
    op.drop_table('experiment_contents')
    ### end Alembic commands ###
