"""empty message

Revision ID: 661880ebfb63
Revises: 7af4d5e1d62d
Create Date: 2017-09-04 17:21:57.528719

"""

# revision identifiers, used by Alembic.
revision = '661880ebfb63'
down_revision = '7af4d5e1d62d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections_to_files',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE')
    )
    op.drop_table('association')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name='association_collection_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='association_file_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('collections_to_files')
    ### end Alembic commands ###
