"""empty message

Revision ID: 6823960cea12
Revises: 3cd316237c29
Create Date: 2017-06-08 21:02:10.571042

"""

# revision identifiers, used by Alembic.
revision = '6823960cea12'
down_revision = '3cd316237c29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('custom_fields', postgresql.JSON(), nullable=True))
    op.add_column('experiments', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('experiments', 'species')
    op.drop_column('experiments', 'experimenter')
    op.drop_column('experiments', 'tissue')
    op.drop_column('experiments', 'information')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('information', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('experiments', sa.Column('tissue', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('experiments', sa.Column('experimenter', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('experiments', sa.Column('species', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('experiments', 'description')
    op.drop_column('experiments', 'custom_fields')
    ### end Alembic commands ###
