"""empty message

Revision ID: 6a501f696d8d
Revises: b0192028b522
Create Date: 2016-10-12 11:03:11.330421

"""

# revision identifiers, used by Alembic.
revision = '6a501f696d8d'
down_revision = 'b0192028b522'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('size_in_bytes', sa.BigInteger(), nullable=True))
    op.drop_column('experiment_files', 'size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('experiment_files', 'size_in_bytes')
    ### end Alembic commands ###
