"""empty message

Revision ID: 6b2a7a7fb693
Revises: 24464b45de58
Create Date: 2017-06-19 14:06:56.349321

"""

# revision identifiers, used by Alembic.
revision = '6b2a7a7fb693'
down_revision = '24464b45de58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_format', sa.String(length=35), nullable=True))
    op.add_column('files', sa.Column('file_format_full', sa.String(length=255), nullable=True))
    op.drop_column('files', 'file_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('files', 'file_format_full')
    op.drop_column('files', 'file_format')
    ### end Alembic commands ###
