"""empty message

Revision ID: 6e65cfdc8f5e
Revises: eee4e5da0be0
Create Date: 2017-04-25 14:31:20.814037

"""

# revision identifiers, used by Alembic.
revision = '6e65cfdc8f5e'
down_revision = 'eee4e5da0be0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot_inputs', sa.Column('required', sa.Boolean(), nullable=True))
    op.drop_column('plot_inputs', 'is_required')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot_inputs', sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('plot_inputs', 'required')
    ### end Alembic commands ###
