"""empty message

Revision ID: 6f3a152e0d45
Revises: df2557e12e2e
Create Date: 2016-12-15 10:42:18.918245

"""

# revision identifiers, used by Alembic.
revision = '6f3a152e0d45'
down_revision = 'df2557e12e2e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploads')
    op.add_column('files', sa.Column('is_upload', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_upload')
    op.create_table('uploads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], [u'experiments.id'], name=u'uploads_experiment_id_fkey', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], [u'files.id'], name=u'uploads_file_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'uploads_pkey')
    )
    ### end Alembic commands ###
