"""empty message

Revision ID: 74f16a793bec
Revises: aff52251e405
Create Date: 2016-11-22 12:01:56.984208

"""

# revision identifiers, used by Alembic.
revision = '74f16a793bec'
down_revision = 'aff52251e405'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipelines')
    op.add_column('experiments', sa.Column('sha', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'sha')
    op.create_table('pipelines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('script', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('definition', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'pipelines_pkey')
    )
    ### end Alembic commands ###
