"""empty message

Revision ID: 75f83007b842
Revises: 792200895eb5
Create Date: 2016-05-08 18:54:35.801071

"""

# revision identifiers, used by Alembic.
revision = '75f83007b842'
down_revision = '792200895eb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('exp_type', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'exp_type')
    ### end Alembic commands ###
