"""empty message

Revision ID: 792200895eb5
Revises: b45f915a86df
Create Date: 2016-05-08 17:37:07.676239

"""

# revision identifiers, used by Alembic.
revision = '792200895eb5'
down_revision = 'b45f915a86df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('experiments', sa.Column('species', sa.String(length=255), nullable=True))
    op.add_column('experiments', sa.Column('tissue', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'tissue')
    op.drop_column('experiments', 'species')
    op.drop_column('experiments', 'date')
    ### end Alembic commands ###
