"""empty message

Revision ID: 7a2fb5df8a61
Revises: 5c99c39f9ef7
Create Date: 2016-04-18 11:10:38.285874

"""

# revision identifiers, used by Alembic.
revision = '7a2fb5df8a61'
down_revision = '5c99c39f9ef7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('filePath', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'filePath')
    ### end Alembic commands ###
