"""empty message

Revision ID: 7f6d30647fcf
Revises: 0fb14b9e8f5c
Create Date: 2016-04-28 16:18:22.786119

"""

# revision identifiers, used by Alembic.
revision = '7f6d30647fcf'
down_revision = '0fb14b9e8f5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_files', 'file_description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('file_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###
