"""empty message

Revision ID: 812b835fd006
Revises: 0c87ed6de8ee
Create Date: 2017-04-03 08:56:56.127003

"""

# revision identifiers, used by Alembic.
revision = '812b835fd006'
down_revision = '0c87ed6de8ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualizations', sa.Column('output_file_id', sa.Integer(), nullable=True))
    op.drop_constraint('visualizations_output_file_fkey', 'visualizations', type_='foreignkey')
    op.create_foreign_key(None, 'visualizations', 'files', ['output_file_id'], ['id'])
    op.drop_column('visualizations', 'output_file')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualizations', sa.Column('output_file', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visualizations', type_='foreignkey')
    op.create_foreign_key('visualizations_output_file_fkey', 'visualizations', 'files', ['output_file'], ['id'])
    op.drop_column('visualizations', 'output_file_id')
    ### end Alembic commands ###
