"""empty message

Revision ID: 8b6a5fce1654
Revises: 7f6d30647fcf
Create Date: 2016-04-30 15:06:06.397275

"""

# revision identifiers, used by Alembic.
revision = '8b6a5fce1654'
down_revision = '7f6d30647fcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('file_size', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_files', 'file_size')
    ### end Alembic commands ###
