"""empty message

Revision ID: 940c36c75db5
Revises: 14cb7ff04dc5
Create Date: 2017-04-10 14:10:54.752602

"""

# revision identifiers, used by Alembic.
revision = '940c36c75db5'
down_revision = '14cb7ff04dc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('visualizations_plot_id_fkey', 'visualizations', type_='foreignkey')
    op.create_foreign_key(None, 'visualizations', 'plots', ['plot_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visualizations', type_='foreignkey')
    op.create_foreign_key('visualizations_plot_id_fkey', 'visualizations', 'experiments', ['plot_id'], ['id'])
    ### end Alembic commands ###
