"""empty message

Revision ID: 95132a821866
Revises: 47879a03e0b7
Create Date: 2016-09-14 16:13:01.935589

"""

# revision identifiers, used by Alembic.
revision = '95132a821866'
down_revision = '47879a03e0b7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('sha', sa.String(length=40), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('group', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('experiment_contents')
    op.drop_constraint(u'experiment_analyses_data_input_fkey', 'experiment_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'experiment_analyses', 'experiment_files', ['data_input'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment_analyses', type_='foreignkey')
    op.create_foreign_key(u'experiment_analyses_data_input_fkey', 'experiment_analyses', 'experiments', ['data_input'], ['id'], ondelete=u'CASCADE')
    op.create_table('experiment_contents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sha', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('mimetype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], [u'experiments.id'], name=u'experiment_contents_experiment_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'experiment_contents_pkey')
    )
    op.drop_table('experiment_files')
    ### end Alembic commands ###
