"""empty message

Revision ID: 99f907d0363e
Revises: abc4c4b261ee
Create Date: 2016-08-10 16:55:14.905867

"""

# revision identifiers, used by Alembic.
revision = '99f907d0363e'
down_revision = 'abc4c4b261ee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('experiment_files', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('experiment_files', 'date_created')
    op.drop_column('experiment_files', 'date_modified')
    op.add_column('experiments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('experiments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('experiments', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('experiments', 'date_created')
    op.drop_column('experiments', 'date_modified')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('date_modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('experiments', sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('experiments', 'date',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('experiments', 'updated_at')
    op.drop_column('experiments', 'created_at')
    op.add_column('experiment_files', sa.Column('date_modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('experiment_files', sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('experiment_files', 'updated_at')
    op.drop_column('experiment_files', 'created_at')
    ### end Alembic commands ###
