"""empty message

Revision ID: 9f433e29dbfa
Revises: 5da2232ea1fe
Create Date: 2017-10-01 15:24:07.145916

"""

# revision identifiers, used by Alembic.
revision = '9f433e29dbfa'
down_revision = '5da2232ea1fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    ### end Alembic commands ###
