"""empty message

Revision ID: a0cfeaf60ee5
Revises: 7a2fb5df8a61
Create Date: 2016-04-21 11:53:12.444789

"""

# revision identifiers, used by Alembic.
revision = 'a0cfeaf60ee5'
down_revision = '7a2fb5df8a61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('filePath', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'experiments', 'filePath')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'experiments', sa.Column('filePath', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('experiment_files')
    ### end Alembic commands ###
