"""empty message

Revision ID: a4b9b2d59b2e
Revises: 812b835fd006
Create Date: 2017-04-03 13:02:02.356004

"""

# revision identifiers, used by Alembic.
revision = 'a4b9b2d59b2e'
down_revision = '812b835fd006'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('pipeline_uid', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'pipeline_uid')
    ### end Alembic commands ###
