"""empty message

Revision ID: adb19af4dd37
Revises: 8b6a5fce1654
Create Date: 2016-05-02 18:21:08.421670

"""

# revision identifiers, used by Alembic.
revision = 'adb19af4dd37'
down_revision = '8b6a5fce1654'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('uid', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_files', 'uid')
    ### end Alembic commands ###
