"""empty message

Revision ID: aff52251e405
Revises: 6a501f696d8d
Create Date: 2016-10-17 17:47:36.622945

"""

# revision identifiers, used by Alembic.
revision = 'aff52251e405'
down_revision = '6a501f696d8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('folder', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_files', 'folder')
    ### end Alembic commands ###
