"""empty message

Revision ID: b0192028b522
Revises: 46874f0ff69f
Create Date: 2016-09-22 17:10:06.692804

"""

# revision identifiers, used by Alembic.
revision = 'b0192028b522'
down_revision = '46874f0ff69f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_analysis_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('experiment_analysis_id', sa.Integer(), nullable=True),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('parameter_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['experiment_analysis_id'], ['experiment_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'experiment_analyses', 'output_parameters')
    op.drop_column(u'experiment_analyses', 'input_parameters')
    op.add_column(u'experiment_files', sa.Column('file_type', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'experiment_files', 'file_type')
    op.add_column(u'experiment_analyses', sa.Column('input_parameters', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column(u'experiment_analyses', sa.Column('output_parameters', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_table('experiment_analysis_parameters')
    ### end Alembic commands ###
