"""empty message

Revision ID: b293dbf40506
Revises: f10f0258343c
Create Date: 2017-05-04 12:30:12.582332

"""

# revision identifiers, used by Alembic.
revision = 'b293dbf40506'
down_revision = 'f10f0258343c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experiments', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.drop_column('experiments', 'user_id')
    ### end Alembic commands ###
