"""empty message

Revision ID: b45f915a86df
Revises: adb19af4dd37
Create Date: 2016-05-06 09:58:24.380718

"""

# revision identifiers, used by Alembic.
revision = 'b45f915a86df'
down_revision = 'adb19af4dd37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('file_group', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_files', 'file_group')
    ### end Alembic commands ###
