"""empty message

Revision ID: b5e7785c3e65
Revises: 6823960cea12
Create Date: 2017-06-09 15:01:13.345806

"""

# revision identifiers, used by Alembic.
revision = 'b5e7785c3e65'
down_revision = '6823960cea12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('age', sa.String(length=40), nullable=True))
    op.add_column('experiments', sa.Column('gender', sa.String(length=40), nullable=True))
    op.add_column('experiments', sa.Column('organism', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'organism')
    op.drop_column('experiments', 'gender')
    op.drop_column('experiments', 'age')
    ### end Alembic commands ###
