"""empty message

Revision ID: c1a82e54f975
Revises: 4d827143949e
Create Date: 2016-08-12 16:06:48.141374

"""

# revision identifiers, used by Alembic.
revision = 'c1a82e54f975'
down_revision = '4d827143949e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_files', sa.Column('file_type', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_files', 'file_type')
    ### end Alembic commands ###
