"""empty message

Revision ID: c9be239778ce
Revises: 940c36c75db5
Create Date: 2017-04-19 16:20:19.530962

"""

# revision identifiers, used by Alembic.
revision = 'c9be239778ce'
down_revision = '940c36c75db5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('output_filename', sa.String(length=40), nullable=True))
    op.drop_column('plots', 'output_file_name')
    op.add_column('visualizations', sa.Column('state', sa.String(length=15), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visualizations', 'state')
    op.add_column('plots', sa.Column('output_file_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('plots', 'output_filename')
    ### end Alembic commands ###
