"""empty message

Revision ID: d90179bfb109
Revises: 661880ebfb63
Create Date: 2017-09-08 15:36:49.185466

"""

# revision identifiers, used by Alembic.
revision = 'd90179bfb109'
down_revision = '661880ebfb63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('annotation', postgresql.JSON(), nullable=True))
    op.drop_column('files', 'experimenter')
    op.drop_column('files', 'gender')
    op.drop_column('files', 'organism')
    op.drop_column('files', 'custom_fields')
    op.drop_column('files', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('age', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('custom_fields', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('organism', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('gender', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('experimenter', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('files', 'annotation')
    ### end Alembic commands ###
