"""empty message

Revision ID: df2557e12e2e
Revises: 110df219fb80
Create Date: 2016-12-14 15:53:33.800567

"""

# revision identifiers, used by Alembic.
revision = 'df2557e12e2e'
down_revision = '110df219fb80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses_parameters', sa.Column('analysis_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'analyses_parameters_experiment_analysis_id_fkey', 'analyses_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'analyses_parameters', 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analyses_parameters', 'experiment_analysis_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses_parameters', sa.Column('experiment_analysis_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analyses_parameters', type_='foreignkey')
    op.create_foreign_key(u'analyses_parameters_experiment_analysis_id_fkey', 'analyses_parameters', 'analyses', ['experiment_analysis_id'], ['id'], ondelete=u'CASCADE')
    op.drop_column('analyses_parameters', 'analysis_id')
    ### end Alembic commands ###
