"""empty message

Revision ID: e0068d8b8587
Revises: 6b2a7a7fb693
Create Date: 2017-09-01 14:16:59.042904

"""

# revision identifiers, used by Alembic.
revision = 'e0068d8b8587'
down_revision = '6b2a7a7fb693'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('analyses_experiment_id_fkey', 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analyses', 'experiment_id')
    op.add_column('files', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('files_experiment_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'experiment_id')
    op.add_column('visualizations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('visualizations_experiment_id_fkey', 'visualizations', type_='foreignkey')
    op.create_foreign_key(None, 'visualizations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('visualizations', 'experiment_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualizations', sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visualizations', type_='foreignkey')
    op.create_foreign_key('visualizations_experiment_id_fkey', 'visualizations', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('visualizations', 'user_id')
    op.add_column('files', sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_experiment_id_fkey', 'files', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'user_id')
    op.add_column('analyses', sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key('analyses_experiment_id_fkey', 'analyses', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analyses', 'user_id')
    ### end Alembic commands ###
