"""empty message

Revision ID: ed67cae191c5
Revises: 74f16a793bec
Create Date: 2016-11-25 09:04:16.221733

"""

# revision identifiers, used by Alembic.
revision = 'ed67cae191c5'
down_revision = '74f16a793bec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_analyses', sa.Column('state', sa.String(length=15), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_analyses', 'state')
    ### end Alembic commands ###
