"""empty message

Revision ID: eee4e5da0be0
Revises: 5dfb178a3ad2
Create Date: 2017-04-25 13:55:33.592458

"""

# revision identifiers, used by Alembic.
revision = 'eee4e5da0be0'
down_revision = '5dfb178a3ad2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot_inputs', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.drop_column('plot_inputs', 'required')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot_inputs', sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('plot_inputs', 'is_required')
    ### end Alembic commands ###
