"""empty message

Revision ID: f10f0258343c
Revises: 1b7190b75b6b
Create Date: 2017-05-04 11:13:17.562381

"""

# revision identifiers, used by Alembic.
revision = 'f10f0258343c'
down_revision = '1b7190b75b6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('group_id', sa.String(length=250), nullable=True))
    op.drop_column('user_groups', 'group_name')
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('fullname', sa.String(length=50), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'email')
    op.add_column('user_groups', sa.Column('group_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('user_groups', 'group_id')
    ### end Alembic commands ###
