"""empty message

Revision ID: fc9c1d2d2bc2
Revises: ed67cae191c5
Create Date: 2016-11-25 14:09:50.572739

"""

# revision identifiers, used by Alembic.
revision = 'fc9c1d2d2bc2'
down_revision = 'ed67cae191c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_analysis_parameters', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('experiment_analysis_parameters', sa.Column('value', sa.String(length=255), nullable=False))
    op.drop_column('experiment_analysis_parameters', 'parameter_value')
    op.drop_column('experiment_analysis_parameters', 'parameter_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_analysis_parameters', sa.Column('parameter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('experiment_analysis_parameters', sa.Column('parameter_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('experiment_analysis_parameters', 'value')
    op.drop_column('experiment_analysis_parameters', 'name')
    ### end Alembic commands ###
