"""empty message

Revision ID: fe1945351dd6
Revises: b5e7785c3e65
Create Date: 2017-06-09 15:24:32.172047

"""

# revision identifiers, used by Alembic.
revision = 'fe1945351dd6'
down_revision = 'b5e7785c3e65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('experimenter', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'experimenter')
    ### end Alembic commands ###
